version: "3"
services:
  hub: 
    image: selenium/hub:4.20
    ports:
    - 4444:4444
  chrome: 
    image: selenium/node-chrome:4.20
    shm_size: '2g'
    depends_on:
        - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1
  firefox: 
    image: selenium/node-firefox:4.20
    shm_size: '2g'
    depends_on:
        - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1
  cucumber_test:
    image: sid0701/java-selenium-cucumber-docker-1
    depends_on:
      - chrome
    volumes:
      - ./docker-output/:/home/output/
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - THREAD_COUNT=3
      - TAGS=@FlightSearch